#Configuración de la base de datos

spring.datasource.url=jdbc:mysql:localhost:3306/plataforma_estudiantil
spring.datasource.username=root
spring.datasource.password=''
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true